return {
  "AstroNvim/astrocommunity",
  -- available plugins can be found at https://github.com/AstroNvim/astrocommunity
  { import = "astrocommunity.pack.lua" },
  { import = "astrocommunity.pack.rust" },
  { import = "astrocommunity.pack.tailwindcss" },
  { import = "astrocommunity.pack.html-css" },
  { import = "astrocommunity.pack.typescript" },
  { import = "astrocommunity.pack.typescript-deno" },
  { import = "astrocommunity.pack.prisma" },
  { import = "astrocommunity.pack.toml" },
  { import = "astrocommunity.pack.yaml" },
  { import = "astrocommunity.pack.json" },
  { import = "astrocommunity.pack.bash" },
  { import = "astrocommunity.pack.docker" },
  { import = "astrocommunity.motion.harpoon" },
  { import = "astrocommunity.editing-support.treej" },
  { import = "astrocommunity.editing-support.todo-comments-nvim" },
  { import = "astrocommunity.media.presence-nvim" },
  { import = "astrocommunity.startup.fsplash-nvim" },
  { import = "astrocommunity.diagnostics.trouble-nvim" },
  { import = "astrocommunity.terminal-integration.vim-tmux-yank" },
  { import = "astrocommunity.note-taking.obsidian-nvim" },
  { import = "astrocommunity.utility.neodim" },
  { import = "astrocommunity.colorscheme.tokyonight-nvim",       enabled = true },
}
